[package]
name = "ez_al"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
linear_model_allen = "0.2.1"
hound = "3.5.1"
